'use client'

import Image from 'next/image'

// All 387 brand logos from filippofilip95/car-logos-dataset
const brandFileMap: Record<string, string> = {
  '9Ff': '9ff.png',
  'Abadal': 'abadal.png',
  'Abarth': 'abarth.png',
  'Abbott Detroit': 'abbott-detroit.jpg',
  'Abt': 'abt.png',
  'Ac': 'ac.png',
  'Acura': 'acura.png',
  'Aiways': 'aiways.png',
  'Aixam': 'aixam.png',
  'Alfa Romeo': 'alfa-romeo.png',
  'Alpina': 'alpina.png',
  'Alpine': 'alpine.png',
  'Alta': 'alta.jpg',
  'Alvis': 'alvis.png',
  'AMC': 'amc.png',
  'Apollo': 'apollo.png',
  'Arash': 'arash.png',
  'Arcfox': 'arcfox.png',
  'Ariel': 'ariel.png',
  'Aro': 'aro.jpg',
  'Arrinera': 'arrinera.png',
  'Arrival': 'arrival.png',
  'Artega': 'artega.png',
  'Ascari': 'ascari.png',
  'Askam': 'askam.png',
  'Aspark': 'aspark.png',
  'Aston Martin': 'aston-martin.png',
  'Atalanta': 'atalanta.png',
  'Auburn': 'auburn.png',
  'Audi Sport': 'audi-sport.png',
  'Audi': 'audi.png',
  'Austin': 'austin.jpg',
  'Autobacs': 'autobacs.jpg',
  'Autobianchi': 'autobianchi.png',
  'Axon': 'axon.png',
  'BAC': 'bac.png',
  'Baic Motor': 'baic-motor.png',
  'Baojun': 'baojun.png',
  'Beiben': 'beiben.png',
  'Bentley': 'bentley.png',
  'Berkeley': 'berkeley.png',
  'Berliet': 'berliet.png',
  'Bertone': 'bertone.png',
  'Bestune': 'bestune.png',
  'Bharatbenz': 'bharatbenz.png',
  'Bitter': 'bitter.png',
  'Bizzarrini': 'bizzarrini.jpg',
  'BMW M': 'bmw-m.png',
  'BMW': 'bmw.png',
  'Borgward': 'borgward.png',
  'Bowler': 'bowler.png',
  'Brabus': 'brabus.png',
  'Brammo': 'brammo.png',
  'Brilliance': 'brilliance.png',
  'Bristol': 'bristol.png',
  'Brooke': 'brooke.png',
  'Bufori': 'bufori.png',
  'Bugatti': 'bugatti.png',
  'Buick': 'buick.png',
  'BYD': 'byd.png',
  'Byton': 'byton.png',
  'Cadillac': 'cadillac.png',
  'Camc': 'camc.png',
  'Canoo': 'canoo.png',
  'Caparo': 'caparo.png',
  'Carlsson': 'carlsson.png',
  'Caterham': 'caterham.png',
  'Changan': 'changan.png',
  'Changfeng': 'changfeng.png',
  'Chery': 'chery.png',
  'Chevrolet Corvette': 'chevrolet-corvette.png',
  'Chevrolet': 'chevrolet.png',
  'Chrysler': 'chrysler.png',
  'Cisitalia': 'cisitalia.png',
  'Citroen': 'citroen.png',
  'Cizeta': 'cizeta.png',
  'Cole': 'cole.png',
  'Corre La Licorne': 'corre-la-licorne.jpg',
  'Cupra': 'cupra.png',
  'Dacia': 'dacia.png',
  'Daewoo': 'daewoo.png',
  'DAF': 'daf.png',
  'Daihatsu': 'daihatsu.png',
  'Daimler': 'daimler.png',
  'Dartz': 'dartz.jpg',
  'Datsun': 'datsun.png',
  'David Brown': 'david-brown.png',
  'Dayun': 'dayun.png',
  'De Tomaso': 'de-tomaso.png',
  'Delage': 'delage.png',
  'Desoto': 'desoto.png',
  'Detroit Electric': 'detroit-electric.png',
  'Devel Sixteen': 'devel-sixteen.png',
  'Diatto': 'diatto.jpg',
  'Dina': 'dina.png',
  'Dkw': 'dkw.jpg',
  'DMC': 'dmc.png',
  'Dodge Viper': 'dodge-viper.png',
  'Dodge': 'dodge.png',
  'Dongfeng': 'dongfeng.png',
  'Donkervoort': 'donkervoort.png',
  'Drako': 'drako.png',
  'DS': 'ds.png',
  'Duesenberg': 'duesenberg.png',
  'Eagle': 'eagle.png',
  'Edag': 'edag.png',
  'Edsel': 'edsel.png',
  'Eicher': 'eicher.png',
  'Elemental': 'elemental.png',
  'Elfin': 'elfin.jpg',
  'Elva': 'elva.png',
  'Englon': 'englon.jpg',
  'ERF': 'erf.png',
  'Eterniti': 'eterniti.jpg',
  'Exeed': 'exeed.png',
  'Facel Vega': 'facel-vega.png',
  'Faraday Future': 'faraday-future.png',
  'FAW Jiefang': 'faw-jiefang.png',
  'FAW': 'faw.png',
  'Ferrari': 'ferrari.png',
  'Fiat': 'fiat.png',
  'Fioravanti': 'fioravanti.jpg',
  'Fisker': 'fisker.png',
  'Foden': 'foden.png',
  'Force Motors': 'force-motors.png',
  'Ford Mustang': 'ford-mustang.png',
  'Ford': 'ford.png',
  'Foton': 'foton.png',
  'FPV': 'fpv.jpg',
  'Franklin': 'franklin.jpg',
  'Freightliner': 'freightliner.png',
  'FSO': 'fso.png',
  'GAC Group': 'gac-group.png',
  'Gardner Douglas': 'gardner-douglas.png',
  'GAZ': 'gaz.png',
  'Geely': 'geely.png',
  'General Motors': 'general-motors.png',
  'Genesis': 'genesis.jpg',
  'Geo': 'geo.png',
  'Geometry': 'geometry.png',
  'Gilbern': 'gilbern.png',
  'Gillet': 'gillet.png',
  'Ginetta': 'ginetta.png',
  'GMC': 'gmc.png',
  'Golden Dragon': 'golden-dragon.png',
  'Gonow': 'gonow.png',
  'Great Wall': 'great-wall.png',
  'Grinnall': 'grinnall.png',
  'Gumpert': 'gumpert.png',
  'Hafei': 'hafei.png',
  'Haima': 'haima.png',
  'Haval': 'haval.png',
  'Hawtai': 'hawtai.png',
  'Hennessey': 'hennessey.png',
  'Higer': 'higer.png',
  'Hillman': 'hillman.jpg',
  'Hindustan Motors': 'hindustan-motors.png',
  'Hino': 'hino.png',
  'Hiphi': 'hiphi.png',
  'Hispano Suiza': 'hispano-suiza.jpg',
  'Holden': 'holden.png',
  'Hommell': 'hommell.png',
  'Honda': 'honda.png',
  'Hongqi': 'hongqi.png',
  'Hongyan': 'hongyan.png',
  'Horch': 'horch.png',
  'HSV': 'hsv.png',
  'Hudson': 'hudson.png',
  'Hummer': 'hummer.png',
  'Hupmobile': 'hupmobile.jpg',
  'Hyundai': 'hyundai.png',
  'IC Bus': 'ic-bus.png',
  'IH': 'ih.png',
  'Ikco': 'ikco.png',
  'Infiniti': 'infiniti.png',
  'Innocenti': 'innocenti.png',
  'Intermeccanica': 'intermeccanica.png',
  'International': 'international.png',
  'Irizar': 'irizar.png',
  'Isdera': 'isdera.jpg',
  'Iso': 'iso.png',
  'Isuzu': 'isuzu.png',
  'Iveco': 'iveco.png',
  'JAC': 'jac.png',
  'Jaguar': 'jaguar.png',
  'Jawa': 'jawa.jpg',
  'JBA Motors': 'jba-motors.png',
  'Jeep': 'jeep.png',
  'Jensen': 'jensen.jpg',
  'Jetour': 'jetour.png',
  'Jetta': 'jetta.png',
  'JMC': 'jmc.png',
  'Kaiser': 'kaiser.jpg',
  'Kamaz': 'kamaz.png',
  'Karlmann King': 'karlmann-king.png',
  'Karma': 'karma.png',
  'Keating': 'keating.png',
  'Kenworth': 'kenworth.png',
  'Kia': 'kia.png',
  'King Long': 'king-long.png',
  'Koenigsegg': 'koenigsegg.png',
  'KTM': 'ktm.png',
  'Lada': 'lada.jpg',
  'Lagonda': 'lagonda.png',
  'Lamborghini': 'lamborghini.png',
  'Lancia': 'lancia.png',
  'Land Rover': 'land-rover.png',
  'Landwind': 'landwind.png',
  'Laraki': 'laraki.png',
  'Leapmotor': 'leapmotor.png',
  'Levc': 'levc.png',
  'Lexus': 'lexus.png',
  'Leyland': 'leyland.png',
  'Li Auto': 'li-auto.png',
  'Lifan': 'lifan.png',
  'Ligier': 'ligier.png',
  'Lincoln': 'lincoln.png',
  'Lister': 'lister.png',
  'Lloyd': 'lloyd.png',
  'Lobini': 'lobini.png',
  'Lordstown': 'lordstown.png',
  'Lotus': 'lotus.png',
  'Lucid': 'lucid.png',
  'Luxgen': 'luxgen.png',
  'Lynk And Co': 'lynk-and-co.png',
  'Mack': 'mack.png',
  'Mahindra': 'mahindra.png',
  'Man': 'man.png',
  'Mansory': 'mansory.png',
  'Marcos': 'marcos.jpg',
  'Marlin': 'marlin.png',
  'Maserati': 'maserati.png',
  'Mastretta': 'mastretta.png',
  'Maxus': 'maxus.png',
  'Maybach': 'maybach.png',
  'MAZ': 'maz.png',
  'Mazda': 'mazda.png',
  'Mazzanti': 'mazzanti.png',
  'McLaren': 'mclaren.png',
  'Melkus': 'melkus.png',
  'Mercedes-AMG': 'mercedes-amg.png',
  'Mercedes-Benz': 'mercedes-benz.png',
  'Mercedes': 'mercedes-benz.png',
  'Mercury': 'mercury.png',
  'Merkur': 'merkur.png',
  'MEV': 'mev.png',
  'MG': 'mg.png',
  'Microcar': 'microcar.png',
  'Mini': 'mini.png',
  'Mitsubishi': 'mitsubishi.png',
  'Mitsuoka': 'mitsuoka.png',
  'Mk': 'mk.png',
  'Morgan': 'morgan.png',
  'Morris': 'morris.jpg',
  'Mosler': 'mosler.png',
  'Navistar': 'navistar.png',
  'Nevs': 'nevs.png',
  'Nikola': 'nikola.png',
  'NIO': 'nio.png',
  'Nissan': 'nissan.png',
  'Noble': 'noble.png',
  'Oldsmobile': 'oldsmobile.png',
  'Oltcit': 'oltcit.png',
  'Omoda': 'omoda.png',
  'Opel': 'opel.png',
  'Osca': 'osca.png',
  'Paccar': 'paccar.png',
  'Packard': 'packard.png',
  'Pagani': 'pagani.png',
  'Panhard': 'panhard.png',
  'Panoz': 'panoz.png',
  'Pegaso': 'pegaso.png',
  'Perodua': 'perodua.png',
  'Peterbilt': 'peterbilt.png',
  'Peugeot': 'peugeot.png',
  'Pgo': 'pgo.jpg',
  'Pierce Arrow': 'pierce-arrow.jpg',
  'Pininfarina': 'pininfarina.png',
  'Plymouth': 'plymouth.png',
  'Polestar': 'polestar.png',
  'Pontiac': 'pontiac.png',
  'Porsche': 'porsche.png',
  'Praga': 'praga.png',
  'Premier': 'premier.png',
  'Prodrive': 'prodrive.png',
  'Proton': 'proton.png',
  'Qoros': 'qoros.png',
  'Radical': 'radical.png',
  'Ram': 'ram.png',
  'Rambler': 'rambler.png',
  'Ranz': 'ranz.png',
  'Renault Samsung': 'renault-samsung.png',
  'Renault': 'renault.png',
  'Rezvani': 'rezvani.png',
  'Riley': 'riley.png',
  'Rimac': 'rimac.png',
  'Rinspeed': 'rinspeed.png',
  'Rivian': 'rivian.png',
  'Roewe': 'roewe.png',
  'Rolls-Royce': 'rolls-royce.png',
  'Ronart': 'ronart.png',
  'Rossion': 'rossion.png',
  'Rover': 'rover.png',
  'Ruf': 'ruf.png',
  'Saab': 'saab.png',
  'SAIC Motor': 'saic-motor.png',
  'Saipa': 'saipa.png',
  'Saleen': 'saleen.jpg',
  'Saturn': 'saturn.png',
  'Scania': 'scania.png',
  'Scion': 'scion.png',
  'Seat': 'seat.png',
  'Setra': 'setra.png',
  'SEV': 'sev.png',
  'Shacman': 'shacman.png',
  'Simca': 'simca.png',
  'Singer': 'singer.png',
  'Singulato': 'singulato.png',
  'Sinotruk': 'sinotruk.png',
  'Sisu': 'sisu.png',
  'Skoda': 'skoda.png',
  'Smart': 'smart.png',
  'Soueast': 'soueast.png',
  'Spania GTA': 'spania-gta.png',
  'Spirra': 'spirra.png',
  'Spyker': 'spyker.png',
  'SsangYong': 'ssangyong.png',
  'SSC': 'ssc.png',
  'Sterling': 'sterling.png',
  'Studebaker': 'studebaker.png',
  'Stutz': 'stutz.png',
  'Subaru': 'subaru.png',
  'Suffolk': 'suffolk.png',
  'Suzuki': 'suzuki.png',
  'Talbot': 'talbot.png',
  'Tata': 'tata.png',
  'Tatra': 'tatra.png',
  'Tauro': 'tauro.png',
  'TechArt': 'techart.png',
  'Tesla': 'tesla.png',
  'Toyota': 'toyota.png',
  'Tramontana': 'tramontana.png',
  'Trion': 'trion.png',
  'Triumph': 'triumph.png',
  'Troller': 'troller.png',
  'Tucker': 'tucker.png',
  'TVR': 'tvr.png',
  'UAZ': 'uaz.png',
  'UD': 'ud.png',
  'Ultima': 'ultima.png',
  'Vandenbrink': 'vandenbrink.jpg',
  'Vauxhall': 'vauxhall.png',
  'Vector': 'vector.png',
  'Vencer': 'vencer.png',
  'Venturi': 'venturi.png',
  'Venucia': 'venucia.png',
  'VinFast': 'vinfast.png',
  'VLF': 'vlf.png',
  'Volkswagen': 'volkswagen.png',
  'Volvo': 'volvo.png',
  'W Motors': 'w-motors.png',
  'Wanderer': 'wanderer.jpg',
  'Wartburg': 'wartburg.png',
  'Weltmeister': 'weltmeister.png',
  'Western Star': 'western-star.png',
  'Westfield': 'westfield.png',
  'Wey': 'wey.png',
  'Wiesmann': 'wiesmann.png',
  'Willys Overland': 'willys-overland.png',
  'Workhorse': 'workhorse.png',
  'Wuling': 'wuling.png',
  'Xpeng': 'xpeng.png',
  'Yulon': 'yulon.png',
  'Yutong': 'yutong.png',
  'Zarooq Motors': 'zarooq-motors.png',
  'Zastava': 'zastava.jpg',
  'ZAZ': 'zaz.png',
  'Zeekr': 'zeekr.png',
  'Zenos': 'zenos.png',
  'Zenvo': 'zenvo.png',
  'Zhongtong': 'zhongtong.png',
  'Zinoro': 'zinoro.png',
  'Zotye': 'zotye.png',
  // Aliases
  'Tofas/Fiat': 'fiat.png',
}

interface BrandLogoProps {
  brand: string
  size?: number
  className?: string
}

export function BrandLogo({ brand, size = 40, className = '' }: BrandLogoProps) {
  const file = brandFileMap[brand] ||
    Object.entries(brandFileMap).find(([key]) => key.toLowerCase() === brand.toLowerCase())?.[1]
  if (!file) {
    return (
      <div
        className={`flex items-center justify-center rounded-full bg-dark-700 ${className}`}
        style={{ width: size, height: size }}
      >
        <span className="text-gray-400 font-bold" style={{ fontSize: size * 0.35 }}>{brand.charAt(0)}</span>
      </div>
    )
  }
  return (
    <Image
      src={`/brands/${file}`}
      alt={`${brand} logo`}
      width={size}
      height={size}
      className={`object-contain ${className}`}
    />
  )
}

// Popular brands in Turkey shown on homepage
export const allBrands = [
  'Volkswagen', 'BMW', 'Mercedes-Benz', 'Audi', 'Toyota', 'Ford',
  'Renault', 'Fiat', 'Hyundai', 'Kia', 'Peugeot', 'Opel',
  'Honda', 'Nissan', 'Skoda', 'Mazda', 'Citroen', 'Volvo',
  'Seat', 'Cupra', 'Mini', 'Jeep', 'Land Rover', 'Porsche',
  'Tesla', 'Dacia', 'Mitsubishi', 'Subaru', 'Suzuki', 'Chevrolet',
  'Jaguar', 'Alfa Romeo', 'Lexus', 'Genesis', 'Ferrari', 'Lamborghini',
  'Maserati', 'Bentley', 'Rolls-Royce', 'Bugatti',
]

export default function BrandLogosSection() {
  return (
    <div className="grid grid-cols-4 sm:grid-cols-5 md:grid-cols-6 lg:grid-cols-8 xl:grid-cols-10 gap-5">
      {allBrands.map((brand) => (
        <div
          key={brand}
          className="flex flex-col items-center gap-2 group"
        >
          <div className="w-16 h-16 rounded-xl bg-dark-900 border border-dark-700 group-hover:border-primary-500/50 flex items-center justify-center transition-all group-hover:scale-110 p-2.5">
            <BrandLogo brand={brand} size={36} />
          </div>
          <span className="text-gray-500 text-[11px] group-hover:text-gray-300 transition-colors text-center leading-tight">{brand}</span>
        </div>
      ))}
    </div>
  )
}
