'use client'

import Image from 'next/image'

// All 387 brand logos from filippofilip95/car-logos-dataset
const brandFileMap: Record<string, string> = {
  '9Ff': '9ff.webp',
  'Abadal': 'abadal.webp',
  'Abarth': 'abarth.webp',
  'Abbott Detroit': 'abbott-detroit.webp',
  'Abt': 'abt.webp',
  'Ac': 'ac.webp',
  'Acura': 'acura.webp',
  'Aiways': 'aiways.webp',
  'Aixam': 'aixam.webp',
  'Alfa Romeo': 'alfa-romeo.webp',
  'Alpina': 'alpina.webp',
  'Alpine': 'alpine.webp',
  'Alta': 'alta.webp',
  'Alvis': 'alvis.webp',
  'AMC': 'amc.webp',
  'Apollo': 'apollo.webp',
  'Arash': 'arash.webp',
  'Arcfox': 'arcfox.webp',
  'Ariel': 'ariel.webp',
  'Aro': 'aro.webp',
  'Arrinera': 'arrinera.webp',
  'Arrival': 'arrival.webp',
  'Artega': 'artega.webp',
  'Ascari': 'ascari.webp',
  'Askam': 'askam.webp',
  'Aspark': 'aspark.webp',
  'Aston Martin': 'aston-martin.webp',
  'Atalanta': 'atalanta.webp',
  'Auburn': 'auburn.webp',
  'Audi Sport': 'audi-sport.webp',
  'Audi': 'audi.webp',
  'Austin': 'austin.webp',
  'Autobacs': 'autobacs.webp',
  'Autobianchi': 'autobianchi.webp',
  'Axon': 'axon.webp',
  'BAC': 'bac.webp',
  'Baic Motor': 'baic-motor.webp',
  'Baojun': 'baojun.webp',
  'Beiben': 'beiben.webp',
  'Bentley': 'bentley.webp',
  'Berkeley': 'berkeley.webp',
  'Berliet': 'berliet.webp',
  'Bertone': 'bertone.webp',
  'Bestune': 'bestune.webp',
  'Bharatbenz': 'bharatbenz.webp',
  'Bitter': 'bitter.webp',
  'Bizzarrini': 'bizzarrini.webp',
  'BMW M': 'bmw-m.webp',
  'BMW': 'bmw.webp',
  'Borgward': 'borgward.webp',
  'Bowler': 'bowler.webp',
  'Brabus': 'brabus.webp',
  'Brammo': 'brammo.webp',
  'Brilliance': 'brilliance.webp',
  'Bristol': 'bristol.webp',
  'Brooke': 'brooke.webp',
  'Bufori': 'bufori.webp',
  'Bugatti': 'bugatti.webp',
  'Buick': 'buick.webp',
  'BYD': 'byd.webp',
  'Byton': 'byton.webp',
  'Cadillac': 'cadillac.webp',
  'Camc': 'camc.webp',
  'Canoo': 'canoo.webp',
  'Caparo': 'caparo.webp',
  'Carlsson': 'carlsson.webp',
  'Caterham': 'caterham.webp',
  'Changan': 'changan.webp',
  'Changfeng': 'changfeng.webp',
  'Chery': 'chery.webp',
  'Chevrolet Corvette': 'chevrolet-corvette.webp',
  'Chevrolet': 'chevrolet.webp',
  'Chrysler': 'chrysler.webp',
  'Cisitalia': 'cisitalia.webp',
  'Citroen': 'citroen.webp',
  'Cizeta': 'cizeta.webp',
  'Cole': 'cole.webp',
  'Corre La Licorne': 'corre-la-licorne.webp',
  'Cupra': 'cupra.webp',
  'Dacia': 'dacia.webp',
  'Daewoo': 'daewoo.webp',
  'DAF': 'daf.webp',
  'Daihatsu': 'daihatsu.webp',
  'Daimler': 'daimler.webp',
  'Dartz': 'dartz.webp',
  'Datsun': 'datsun.webp',
  'David Brown': 'david-brown.webp',
  'Dayun': 'dayun.webp',
  'De Tomaso': 'de-tomaso.webp',
  'Delage': 'delage.webp',
  'Desoto': 'desoto.webp',
  'Detroit Electric': 'detroit-electric.webp',
  'Devel Sixteen': 'devel-sixteen.webp',
  'Diatto': 'diatto.webp',
  'Dina': 'dina.webp',
  'Dkw': 'dkw.webp',
  'DMC': 'dmc.webp',
  'Dodge Viper': 'dodge-viper.webp',
  'Dodge': 'dodge.webp',
  'Dongfeng': 'dongfeng.webp',
  'Donkervoort': 'donkervoort.webp',
  'Drako': 'drako.webp',
  'DS': 'ds.webp',
  'Duesenberg': 'duesenberg.webp',
  'Eagle': 'eagle.webp',
  'Edag': 'edag.webp',
  'Edsel': 'edsel.webp',
  'Eicher': 'eicher.webp',
  'Elemental': 'elemental.webp',
  'Elfin': 'elfin.webp',
  'Elva': 'elva.webp',
  'Englon': 'englon.webp',
  'ERF': 'erf.webp',
  'Eterniti': 'eterniti.webp',
  'Exeed': 'exeed.webp',
  'Facel Vega': 'facel-vega.webp',
  'Faraday Future': 'faraday-future.webp',
  'FAW Jiefang': 'faw-jiefang.webp',
  'FAW': 'faw.webp',
  'Ferrari': 'ferrari.webp',
  'Fiat': 'fiat.webp',
  'Fioravanti': 'fioravanti.webp',
  'Fisker': 'fisker.webp',
  'Foden': 'foden.webp',
  'Force Motors': 'force-motors.webp',
  'Ford Mustang': 'ford-mustang.webp',
  'Ford': 'ford.webp',
  'Foton': 'foton.webp',
  'FPV': 'fpv.webp',
  'Franklin': 'franklin.webp',
  'Freightliner': 'freightliner.webp',
  'FSO': 'fso.webp',
  'GAC Group': 'gac-group.webp',
  'Gardner Douglas': 'gardner-douglas.webp',
  'GAZ': 'gaz.webp',
  'Geely': 'geely.webp',
  'General Motors': 'general-motors.webp',
  'Genesis': 'genesis.webp',
  'Geo': 'geo.webp',
  'Geometry': 'geometry.webp',
  'Gilbern': 'gilbern.webp',
  'Gillet': 'gillet.webp',
  'Ginetta': 'ginetta.webp',
  'GMC': 'gmc.webp',
  'Golden Dragon': 'golden-dragon.webp',
  'Gonow': 'gonow.webp',
  'Great Wall': 'great-wall.webp',
  'Grinnall': 'grinnall.webp',
  'Gumpert': 'gumpert.webp',
  'Hafei': 'hafei.webp',
  'Haima': 'haima.webp',
  'Haval': 'haval.webp',
  'Hawtai': 'hawtai.webp',
  'Hennessey': 'hennessey.webp',
  'Higer': 'higer.webp',
  'Hillman': 'hillman.webp',
  'Hindustan Motors': 'hindustan-motors.webp',
  'Hino': 'hino.webp',
  'Hiphi': 'hiphi.webp',
  'Hispano Suiza': 'hispano-suiza.webp',
  'Holden': 'holden.webp',
  'Hommell': 'hommell.webp',
  'Honda': 'honda.webp',
  'Hongqi': 'hongqi.webp',
  'Hongyan': 'hongyan.webp',
  'Horch': 'horch.webp',
  'HSV': 'hsv.webp',
  'Hudson': 'hudson.webp',
  'Hummer': 'hummer.webp',
  'Hupmobile': 'hupmobile.webp',
  'Hyundai': 'hyundai.webp',
  'IC Bus': 'ic-bus.webp',
  'IH': 'ih.webp',
  'Ikco': 'ikco.webp',
  'Infiniti': 'infiniti.webp',
  'Innocenti': 'innocenti.webp',
  'Intermeccanica': 'intermeccanica.webp',
  'International': 'international.webp',
  'Irizar': 'irizar.webp',
  'Isdera': 'isdera.webp',
  'Iso': 'iso.webp',
  'Isuzu': 'isuzu.webp',
  'Iveco': 'iveco.webp',
  'JAC': 'jac.webp',
  'Jaguar': 'jaguar.webp',
  'Jawa': 'jawa.webp',
  'JBA Motors': 'jba-motors.webp',
  'Jeep': 'jeep.webp',
  'Jensen': 'jensen.webp',
  'Jetour': 'jetour.webp',
  'Jetta': 'jetta.webp',
  'JMC': 'jmc.webp',
  'Kaiser': 'kaiser.webp',
  'Kamaz': 'kamaz.webp',
  'Karlmann King': 'karlmann-king.webp',
  'Karma': 'karma.webp',
  'Keating': 'keating.webp',
  'Kenworth': 'kenworth.webp',
  'Kia': 'kia.webp',
  'King Long': 'king-long.webp',
  'Koenigsegg': 'koenigsegg.webp',
  'KTM': 'ktm.webp',
  'Lada': 'lada.webp',
  'Lagonda': 'lagonda.webp',
  'Lamborghini': 'lamborghini.webp',
  'Lancia': 'lancia.webp',
  'Land Rover': 'land-rover.webp',
  'Landwind': 'landwind.webp',
  'Laraki': 'laraki.webp',
  'Leapmotor': 'leapmotor.webp',
  'Levc': 'levc.webp',
  'Lexus': 'lexus.webp',
  'Leyland': 'leyland.webp',
  'Li Auto': 'li-auto.webp',
  'Lifan': 'lifan.webp',
  'Ligier': 'ligier.webp',
  'Lincoln': 'lincoln.webp',
  'Lister': 'lister.webp',
  'Lloyd': 'lloyd.webp',
  'Lobini': 'lobini.webp',
  'Lordstown': 'lordstown.webp',
  'Lotus': 'lotus.webp',
  'Lucid': 'lucid.webp',
  'Luxgen': 'luxgen.webp',
  'Lynk And Co': 'lynk-and-co.webp',
  'Mack': 'mack.webp',
  'Mahindra': 'mahindra.webp',
  'Man': 'man.webp',
  'Mansory': 'mansory.webp',
  'Marcos': 'marcos.webp',
  'Marlin': 'marlin.webp',
  'Maserati': 'maserati.webp',
  'Mastretta': 'mastretta.webp',
  'Maxus': 'maxus.webp',
  'Maybach': 'maybach.webp',
  'MAZ': 'maz.webp',
  'Mazda': 'mazda.webp',
  'Mazzanti': 'mazzanti.webp',
  'McLaren': 'mclaren.webp',
  'Melkus': 'melkus.webp',
  'Mercedes-AMG': 'mercedes-amg.webp',
  'Mercedes-Benz': 'mercedes-benz.webp',
  'Mercedes': 'mercedes-benz.webp',
  'Mercury': 'mercury.webp',
  'Merkur': 'merkur.webp',
  'MEV': 'mev.webp',
  'MG': 'mg.webp',
  'Microcar': 'microcar.webp',
  'Mini': 'mini.webp',
  'Mitsubishi': 'mitsubishi.webp',
  'Mitsuoka': 'mitsuoka.webp',
  'Mk': 'mk.webp',
  'Morgan': 'morgan.webp',
  'Morris': 'morris.webp',
  'Mosler': 'mosler.webp',
  'Navistar': 'navistar.webp',
  'Nevs': 'nevs.webp',
  'Nikola': 'nikola.webp',
  'NIO': 'nio.webp',
  'Nissan': 'nissan.webp',
  'Noble': 'noble.webp',
  'Oldsmobile': 'oldsmobile.webp',
  'Oltcit': 'oltcit.webp',
  'Omoda': 'omoda.webp',
  'Opel': 'opel.webp',
  'Osca': 'osca.webp',
  'Paccar': 'paccar.webp',
  'Packard': 'packard.webp',
  'Pagani': 'pagani.webp',
  'Panhard': 'panhard.webp',
  'Panoz': 'panoz.webp',
  'Pegaso': 'pegaso.webp',
  'Perodua': 'perodua.webp',
  'Peterbilt': 'peterbilt.webp',
  'Peugeot': 'peugeot.webp',
  'Pgo': 'pgo.webp',
  'Pierce Arrow': 'pierce-arrow.webp',
  'Pininfarina': 'pininfarina.webp',
  'Plymouth': 'plymouth.webp',
  'Polestar': 'polestar.webp',
  'Pontiac': 'pontiac.webp',
  'Porsche': 'porsche.webp',
  'Praga': 'praga.webp',
  'Premier': 'premier.webp',
  'Prodrive': 'prodrive.webp',
  'Proton': 'proton.webp',
  'Qoros': 'qoros.webp',
  'Radical': 'radical.webp',
  'Ram': 'ram.webp',
  'Rambler': 'rambler.webp',
  'Ranz': 'ranz.webp',
  'Renault Samsung': 'renault-samsung.webp',
  'Renault': 'renault.webp',
  'Rezvani': 'rezvani.webp',
  'Riley': 'riley.webp',
  'Rimac': 'rimac.webp',
  'Rinspeed': 'rinspeed.webp',
  'Rivian': 'rivian.webp',
  'Roewe': 'roewe.webp',
  'Rolls-Royce': 'rolls-royce.webp',
  'Ronart': 'ronart.webp',
  'Rossion': 'rossion.webp',
  'Rover': 'rover.webp',
  'Ruf': 'ruf.webp',
  'Saab': 'saab.webp',
  'SAIC Motor': 'saic-motor.webp',
  'Saipa': 'saipa.webp',
  'Saleen': 'saleen.webp',
  'Saturn': 'saturn.webp',
  'Scania': 'scania.webp',
  'Scion': 'scion.webp',
  'Seat': 'seat.webp',
  'Setra': 'setra.webp',
  'SEV': 'sev.webp',
  'Shacman': 'shacman.webp',
  'Simca': 'simca.webp',
  'Singer': 'singer.webp',
  'Singulato': 'singulato.webp',
  'Sinotruk': 'sinotruk.webp',
  'Sisu': 'sisu.webp',
  'Skoda': 'skoda.webp',
  'Smart': 'smart.webp',
  'Soueast': 'soueast.webp',
  'Spania GTA': 'spania-gta.webp',
  'Spirra': 'spirra.webp',
  'Spyker': 'spyker.webp',
  'SsangYong': 'ssangyong.webp',
  'SSC': 'ssc.webp',
  'Sterling': 'sterling.webp',
  'Studebaker': 'studebaker.webp',
  'Stutz': 'stutz.webp',
  'Subaru': 'subaru.webp',
  'Suffolk': 'suffolk.webp',
  'Suzuki': 'suzuki.webp',
  'Talbot': 'talbot.webp',
  'Tata': 'tata.webp',
  'Tatra': 'tatra.webp',
  'Tauro': 'tauro.webp',
  'TechArt': 'techart.webp',
  'Tesla': 'tesla.webp',
  'Toyota': 'toyota.webp',
  'Tramontana': 'tramontana.webp',
  'Trion': 'trion.webp',
  'Triumph': 'triumph.webp',
  'Troller': 'troller.webp',
  'Tucker': 'tucker.webp',
  'TVR': 'tvr.webp',
  'UAZ': 'uaz.webp',
  'UD': 'ud.webp',
  'Ultima': 'ultima.webp',
  'Vandenbrink': 'vandenbrink.webp',
  'Vauxhall': 'vauxhall.webp',
  'Vector': 'vector.webp',
  'Vencer': 'vencer.webp',
  'Venturi': 'venturi.webp',
  'Venucia': 'venucia.webp',
  'VinFast': 'vinfast.webp',
  'VLF': 'vlf.webp',
  'Volkswagen': 'volkswagen.webp',
  'Volvo': 'volvo.webp',
  'W Motors': 'w-motors.webp',
  'Wanderer': 'wanderer.webp',
  'Wartburg': 'wartburg.webp',
  'Weltmeister': 'weltmeister.webp',
  'Western Star': 'western-star.webp',
  'Westfield': 'westfield.webp',
  'Wey': 'wey.webp',
  'Wiesmann': 'wiesmann.webp',
  'Willys Overland': 'willys-overland.webp',
  'Workhorse': 'workhorse.webp',
  'Wuling': 'wuling.webp',
  'Xpeng': 'xpeng.webp',
  'Yulon': 'yulon.webp',
  'Yutong': 'yutong.webp',
  'Zarooq Motors': 'zarooq-motors.webp',
  'Zastava': 'zastava.webp',
  'ZAZ': 'zaz.webp',
  'Zeekr': 'zeekr.webp',
  'Zenos': 'zenos.webp',
  'Zenvo': 'zenvo.webp',
  'Zhongtong': 'zhongtong.webp',
  'Zinoro': 'zinoro.webp',
  'Zotye': 'zotye.webp',
  // Aliases
  'Tofas/Fiat': 'fiat.webp',
}

interface BrandLogoProps {
  brand: string
  size?: number
  className?: string
}

export function BrandLogo({ brand, size = 40, className = '' }: BrandLogoProps) {
  const file = brandFileMap[brand] ||
    Object.entries(brandFileMap).find(([key]) => key.toLowerCase() === brand.toLowerCase())?.[1]
  if (!file) {
    return (
      <div
        className={`flex items-center justify-center rounded-full bg-dark-700 ${className}`}
        style={{ width: size, height: size }}
      >
        <span className="text-gray-400 font-bold" style={{ fontSize: size * 0.35 }}>{brand.charAt(0)}</span>
      </div>
    )
  }
  return (
    <Image
      src={`/brands/${file}`}
      alt={`${brand} logo`}
      width={size}
      height={size}
      className={`object-contain ${className}`}
    />
  )
}

// Marka adından logo URL'i döndürür (src olarak kullanılabilir)
export function getBrandLogoUrl(brand: string): string | null {
  const file = brandFileMap[brand] ||
    Object.entries(brandFileMap).find(([key]) => key.toLowerCase() === brand.toLowerCase())?.[1]
  return file ? `/brands/${file}` : null
}

// Popular brands in Turkey shown on homepage
export const allBrands = [
  'Volkswagen', 'BMW', 'Mercedes-Benz', 'Audi', 'Toyota', 'Ford',
  'Renault', 'Fiat', 'Hyundai', 'Kia', 'Peugeot', 'Opel',
  'Honda', 'Nissan', 'Skoda', 'Mazda', 'Citroen', 'Volvo',
  'Seat', 'Cupra', 'Mini', 'Jeep', 'Land Rover', 'Porsche',
  'Tesla', 'Dacia', 'Mitsubishi', 'Subaru', 'Suzuki', 'Chevrolet',
  'Jaguar', 'Alfa Romeo', 'Lexus', 'Genesis', 'Ferrari', 'Lamborghini',
  'Maserati', 'Bentley', 'Rolls-Royce', 'Bugatti',
]

export default function BrandLogosSection() {
  return (
    <div className="grid grid-cols-4 sm:grid-cols-5 md:grid-cols-6 lg:grid-cols-8 xl:grid-cols-10 gap-5">
      {allBrands.map((brand) => (
        <div
          key={brand}
          className="flex flex-col items-center gap-2 group"
        >
          <div className="w-16 h-16 rounded-xl bg-dark-900 border border-dark-700 group-hover:border-primary-500/50 flex items-center justify-center transition-all group-hover:scale-110 p-2.5">
            <BrandLogo brand={brand} size={36} />
          </div>
          <span className="text-gray-500 text-[11px] group-hover:text-gray-300 transition-colors text-center leading-tight">{brand}</span>
        </div>
      ))}
    </div>
  )
}
